[package]
name = "blog-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tokio-stream = "0.1.17"
ratatui = "0.29.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
tui-input = "0.14.0"
